#! /bin/bash
mv .git .git-backup
git init
bzr fast-export --plain --git-branch=master | git fast-import
git remote add origin git@github.com:FabriceSalvaire/linear-delta-robot.git
git push origin --force
# End
